name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: docker-react
    steps:
      - uses: actions/checkout@v2

      # Debugging to confirm secrets (ensure sensitive values are NOT exposed in logs)
      - run: echo "${{ vars.DOCKERHUB_USERNAME }} ${{ vars.DOCKERHUB_PASSWORD }}"
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t cygnetops/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true cygnetops/react-test npm test
