name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: docker-react
    steps:
      - uses: actions/checkout@v2

      # Debugging to confirm secrets (ensure sensitive values are NOT exposed in logs)
      - run: echo "US ${{ vars.DOCKERHUB_USERNAME }} PS ${{ vars.DOCKERHUB_PASSWORD }}"
      - run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - run: docker build -t VadimZavgorodny/docker-react -f Dockerfile.dev .
      - run: docker run -e CI=true VadimZavgorodny/docker-react npm test
